import "./globals.css";

import Footer from "@/components/Footer";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col overflow-hidden">
          <NavBar />
          <div className="mt-[60px]">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
