import "./globals.css";

import Footer from "@/components/Footer";
import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar";
import Providers from "@/components/Providers";
import { ReactNode } from "react";
import { getServerSession } from "next-auth"

interface Props {
  children: ReactNode;
}

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Exchanger App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Props) {
  const session = await getServerSession()
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={session}>
          <main className="flex flex-col overflow-x-hidden">
            <NavBar />
            {children}
            <Footer />
          </main>
        </Providers>
      </body>
    </html>
  );
}
