export const directionsData = [
  {
    date: "25 мар. 2020 09:51:10",
    direction_from: "Payeer",
    direction_to: "Yandex Money",
    currency_from: "RUB",
    currency_to: "USD",
    status: true,
    rate_from: "1.0047",
    rate_to: "1",
    process: "Полуавтоматический",
  },
  {
    date: "25 мар. 2020 09:51:10",
    direction_from: "Payeer",
    direction_to: "Payeer",
    currency_from: "USD",
    currency_to: "RUB",
    status: true,
    rate_from: "76.965",
    rate_to: "1",
    process: "Полуавтоматический",
  },
  {
    date: "27 мар. 2020 09:51:10",
    direction_from: "Yandex Money",
    direction_to: "Payeer",
    currency_from: "RUB",
    currency_to: "RUB",
    status: false,
    rate_from: "76.456",
    rate_to: "76.5",
    process: "Полуавтоматический",
  }
]