export const pairsData = [
  {
    id: 1,
    source_id: "cbr",
    source: "CBR.RU",
    title: "AUD-RUB",
    pair: "AUD-RUB",
    nominal: 1,
    rate: "60.0",
    code: "cbr_audrub",
    formula: "NULL",
  },
  {
    id: 2,
    source_id: "cbr",
    source: "CBR.RU",
    title: "RUB-AUD",
    pair: "RUB-AUD",
    nominal: 1,
    rate: "0.016",
    code: "cbr_rubaud_reverse",
    formula: "NULL",
  },
  {
    id: 3,
    source_id: "cbr",
    source: "CBR.RU",
    title: "AZN-RUB",
    pair: "AZN-RUB",
    nominal: 1,
    rate: "53.0",
    code: "cbr_aznrub",
    formula: "NULL",
  },
]